# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\dwfen\Documents\Фильтры\filters\filter_table.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_filter_table(object):
    def setupUi(self, filter_table):
        filter_table.setObjectName("filter_table")
        filter_table.resize(438, 521)
        self.gridLayout_5 = QtWidgets.QGridLayout(filter_table)
        self.gridLayout_5.setObjectName("gridLayout_5")
        spacerItem = QtWidgets.QSpacerItem(20, 120, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_5.addItem(spacerItem, 0, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem1, 1, 0, 1, 1)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.tableWidget = QtWidgets.QTableWidget(filter_table)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.tableWidget.horizontalHeader().setCascadingSectionResizes(False)
        self.tableWidget.verticalHeader().setCascadingSectionResizes(True)
        self.tableWidget.verticalHeader().setSortIndicatorShown(True)
        self.gridLayout_3.addWidget(self.tableWidget, 1, 1, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem2, 0, 1, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem3, 2, 1, 1, 1)
        self.gridLayout_5.addLayout(self.gridLayout_3, 1, 1, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem4, 1, 2, 1, 1)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.Image = QtWidgets.QLabel(filter_table)
        self.Image.setText("")
        self.Image.setAlignment(QtCore.Qt.AlignCenter)
        self.Image.setObjectName("Image")
        self.gridLayout_2.addWidget(self.Image, 0, 0, 1, 1)
        self.ACHH = QtWidgets.QLabel(filter_table)
        self.ACHH.setText("")
        self.ACHH.setAlignment(QtCore.Qt.AlignCenter)
        self.ACHH.setObjectName("ACHH")
        self.gridLayout_2.addWidget(self.ACHH, 0, 1, 1, 1)
        self.gridLayout_5.addLayout(self.gridLayout_2, 2, 1, 1, 1)
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.INFO = QtWidgets.QLabel(filter_table)
        self.INFO.setText("")
        self.INFO.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.INFO.setObjectName("INFO")
        self.gridLayout_4.addWidget(self.INFO, 0, 0, 1, 1)
        self.gridLayout_5.addLayout(self.gridLayout_4, 3, 1, 1, 1)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton_2 = QtWidgets.QPushButton(filter_table)
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout.addWidget(self.pushButton_2, 0, 0, 1, 1)
        self.pushButton = QtWidgets.QPushButton(filter_table)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 0, 1, 1, 1)
        self.gridLayout_5.addLayout(self.gridLayout, 4, 1, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(20, 120, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_5.addItem(spacerItem5, 5, 1, 1, 1)

        self.retranslateUi(filter_table)
        QtCore.QMetaObject.connectSlotsByName(filter_table)

    def retranslateUi(self, filter_table):
        _translate = QtCore.QCoreApplication.translate
        filter_table.setWindowTitle(_translate("filter_table", "Form"))
        self.pushButton_2.setText(_translate("filter_table", "Сохранить расчет "))
        self.pushButton.setText(_translate("filter_table", "Закрыть"))
